language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.3.2
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.4.1
  - DJANGO_VERSION=1.4.2
install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .
script:
  - ./run_tests.py
branches:
  only:
    - master
    - develop
